name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  chore:
    name: Testing chores
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 16.x
      uses: actions/setup-node@master
      with:
        node-version: 16.x

    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Check for type errors
      run: yarn tsc
      shell: bash

    - name: Check for linting errors (fix w/ "yarn lint --fix")
      run: yarn lint
      shell: bash

  test:
    strategy:
      fail-fast: false
      matrix:
        node:
        - 12
        - 14
        - 16
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    name: ${{matrix.platform}} w/ Node.js ${{matrix.node}}.x
    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js ${{matrix.node}}
      uses: actions/setup-node@master
      with:
        node-version: ${{matrix.node}}

    - name: Install shells
      if: ${{ matrix.platform != 'windows-latest' }}
      # bash and pwsh are installed by default in GH actions
      # images, but the bash version that gets installed on
      # macos is from 2014
      run: brew install bash zsh fish
      shell: bash

    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Run the integration tests
      run: yarn test
      shell: bash

    - name: Run the e2e tests
      run: yarn test:e2e
      shell: bash
