name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
        - 12
        - 14
        - 16
        platform:
        - ubuntu-latest
        - macos-latest
        # - windows-latest

    name: '${{matrix.platform}} w/ Node.js ${{matrix.node}}.x'
    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{matrix.node}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node}}

    - name: Install shells
      # bash and pwsh are installed by default in GH actions
      # images, but the bash version that gets installed on
      # macos is from 2014
      run: brew install bash zsh fish

    - run: yarn
    - run: yarn tsc
    - run: yarn test
    - run: yarn test:e2e
    - run: yarn lint
